-- Up Migration
ALTER TABLE "public"."dnd_5e_character_proficiencies"
ADD COLUMN "acrobatics_mod" int4,
ADD COLUMN "animal_handling_mod" int4,
ADD COLUMN "arcana_mod" int4,
ADD COLUMN "athletics_mod" int4,
ADD COLUMN "deception_mod" int4,
ADD COLUMN "history_mod" int4,
ADD COLUMN "insight_mod" int4,
ADD COLUMN "intimidation_mod" int4,
ADD COLUMN "investigation_mod" int4,
ADD COLUMN "medicine_mod" int4,
ADD COLUMN "nature_mod" int4,
ADD COLUMN "perception_mod" int4,
ADD COLUMN "performance_mod" int4,
ADD COLUMN "persuasion_mod" int4,
ADD COLUMN "religion_mod" int4,
ADD COLUMN "sleight_of_hand_mod" int4,
ADD COLUMN "stealth_mod" int4,
ADD COLUMN "survival_mod" int4;
-- Down Migration
ALTER TABLE "public"."dnd_5e_character_proficiencies"
DROP COLUMN "acrobatics_mod",
DROP COLUMN "animal_handling_mod",
DROP COLUMN "arcana_mod",
DROP COLUMN "athletics_mod",
DROP COLUMN "deception_mod",
DROP COLUMN "history_mod",
DROP COLUMN "insight_mod",
DROP COLUMN "intimidation_mod",
DROP COLUMN "investigation_mod",
DROP COLUMN "medicine_mod",
DROP COLUMN "nature_mod",
DROP COLUMN "perception_mod",
DROP COLUMN "performance_mod",
DROP COLUMN "persuasion_mod",
DROP COLUMN "religion_mod",
DROP COLUMN "sleight_of_hand_mod",
DROP COLUMN "stealth_mod",
DROP COLUMN "survival_mod";