-- Up Migration
ALTER TABLE public."dnd_5e_character_general"
DROP COLUMN IF EXISTS "race",
DROP COLUMN IF EXISTS "class",
DROP COLUMN IF EXISTS "level",
DROP COLUMN IF EXISTS "exp",
DROP COLUMN IF EXISTS "inspiration",
DROP COLUMN IF EXISTS "initiative",
DROP COLUMN IF EXISTS "speed",
DROP COLUMN IF EXISTS "armor_class",
DROP COLUMN IF EXISTS "current_hp",
DROP COLUMN IF EXISTS "temp_hp",
DROP COLUMN IF EXISTS "hit_dice",
DROP COLUMN IF EXISTS "strength",
DROP COLUMN IF EXISTS "dexterity",
DROP COLUMN IF EXISTS "constitution",
DROP COLUMN IF EXISTS "intelligence",
DROP COLUMN IF EXISTS "wisdom",
DROP COLUMN IF EXISTS "charisma",
DROP COLUMN IF EXISTS "max_hp",
DROP COLUMN IF EXISTS "hit_dice_total",
DROP COLUMN IF EXISTS "class_resource",
DROP COLUMN IF EXISTS "class_resource_total",
DROP COLUMN IF EXISTS "other_resource",
DROP COLUMN IF EXISTS "other_resource_total",
DROP COLUMN IF EXISTS "class_resource_title",
DROP COLUMN IF EXISTS "other_resource_title",
DROP COLUMN IF EXISTS "ds_success_1",
DROP COLUMN IF EXISTS "ds_success_2",
DROP COLUMN IF EXISTS "ds_success_3",
DROP COLUMN IF EXISTS "ds_failure_1",
DROP COLUMN IF EXISTS "ds_failure_2",
DROP COLUMN IF EXISTS "ds_failure_3",
DROP COLUMN IF EXISTS "wisdom_mod",
DROP COLUMN IF EXISTS "subclass",
DROP COLUMN IF EXISTS "other_class",
DROP COLUMN IF EXISTS "copper",
DROP COLUMN IF EXISTS "silver",
DROP COLUMN IF EXISTS "electrum",
DROP COLUMN IF EXISTS "gold",
DROP COLUMN IF EXISTS "platinum";

-- Down Migration
ALTER TABLE public."dnd_5e_character_general"
ADD COLUMN IF NOT EXISTS "race" varchar,
ADD COLUMN IF NOT EXISTS "class" varchar,
ADD COLUMN IF NOT EXISTS "level" int2,
ADD COLUMN IF NOT EXISTS "exp" int4,
ADD COLUMN IF NOT EXISTS "inspiration" bool NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "initiative" float4,
ADD COLUMN IF NOT EXISTS "speed" int2,
ADD COLUMN IF NOT EXISTS "armor_class" int2,
ADD COLUMN IF NOT EXISTS "current_hp" int2,
ADD COLUMN IF NOT EXISTS "temp_hp" int2,
ADD COLUMN IF NOT EXISTS "hit_dice" int2,
ADD COLUMN IF NOT EXISTS "strength" int2,
ADD COLUMN IF NOT EXISTS "dexterity" int2,
ADD COLUMN IF NOT EXISTS "constitution" int2,
ADD COLUMN IF NOT EXISTS "intelligence" int2,
ADD COLUMN IF NOT EXISTS "wisdom" int2,
ADD COLUMN IF NOT EXISTS "charisma" int2,
ADD COLUMN IF NOT EXISTS "max_hp" int2,
ADD COLUMN IF NOT EXISTS "hit_dice_total" varchar,
ADD COLUMN IF NOT EXISTS "class_resource" int2,
ADD COLUMN IF NOT EXISTS "class_resource_total" int2,
ADD COLUMN IF NOT EXISTS "other_resource" varchar,
ADD COLUMN IF NOT EXISTS "other_resource_total" int2,
ADD COLUMN IF NOT EXISTS "class_resource_title" varchar,
ADD COLUMN IF NOT EXISTS "other_resource_title" varchar,
ADD COLUMN IF NOT EXISTS "ds_success_1" bool DEFAULT false,
ADD COLUMN IF NOT EXISTS "ds_success_2" bool DEFAULT false,
ADD COLUMN IF NOT EXISTS "ds_success_3" bool DEFAULT false,
ADD COLUMN IF NOT EXISTS "ds_failure_1" bool DEFAULT false,
ADD COLUMN IF NOT EXISTS "ds_failure_2" bool DEFAULT false,
ADD COLUMN IF NOT EXISTS "ds_failure_3" bool DEFAULT false,
ADD COLUMN IF NOT EXISTS "wisdom_mod" int2,
ADD COLUMN IF NOT EXISTS "subclass" varchar,
ADD COLUMN IF NOT EXISTS "other_class" varchar,
ADD COLUMN IF NOT EXISTS "copper" int4,
ADD COLUMN IF NOT EXISTS "silver" int4,
ADD COLUMN IF NOT EXISTS "electrum" int4,
ADD COLUMN IF NOT EXISTS "gold" int4,
ADD COLUMN IF NOT EXISTS "platinum" int4;
